name: 'Node Cache Action'
description: 'Zero-config cache for Node.js dependencies (npm/pnpm/yarn/bun)'
author: 'maou-shonen'
branding:
  icon: 'package'
  color: 'blue'

outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the cache key'
  package-manager:
    description: 'Detected package manager (npm, pnpm, yarn, or bun)'
  lockfile:
    description: 'Detected lockfile path'
  cache-paths:
    description: 'Cache paths being used'
  cache-key:
    description: 'Generated cache key'

runs:
  using: 'node24'
  main: 'dist/main/index.js'
  post: 'dist/cache-save/index.js'
